baseurl      = "https://darkodjalevski.me/"
title        = "Darko Djalevski"
languageCode = "en-us"
theme        = "dd"
paginate     = 10


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
   footerLeft = "<a></a>"
   footerRight = "<a></a>"

  # Subtitle for home
  homeSubtitle = "Software Engineer /Go Mage"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you link
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Darko Djalevski Blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Darko Djalevski"
    keywords = ""
    copyright = 'Darko Djalevski'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
    logoMark     = "»"
    logoText = "cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
[[menu.main]]
identifier = "stack"
name       = "Stack"
url        = "stack/"
images = ["static/images/struct.png"]


  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:dare_zalevski@yahoo.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Dzalevski"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/darkodjalevski/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/9807296/dzalevski"

[params.footer]
  trademark = true
  copyright = true

